### PR TITLE
Enable the hw codec in SRIOV mode

### PR DESCRIPTION
**Pull request by yhe39**
The video format have scanout flag but need use i915 driver
to allocate.

Tracked-On: OAM-101728
Signed-off-by: HeYue <yue.he@intel.com>

### CODE REVIEW

**Review by feijiang1 — APPROVED** [review]

**Comment by yhe39** [comment]
hi @YuanjunHuang  , could you help to review this patch.
i verify on adl, the sriov, gvt-d use hw codec video playback well.

**Comment by yhe39** [comment]
hi @renchenglei , could you help to review this patch :)

**Comment by yhe39** [comment]
hi @feijiang1  @YuanjunHuang  @renchenglei  could you help to review this patch? modify a little.

**Review by feijiang1 — APPROVED** [review]

**Review by renchenglei — APPROVED** [review]
LGTM, thanks

**Review by YuanjunHuang — APPROVED** [review]

**Pull request merged**
